import { jsPDF } from "jspdf";

// Brand palette (RGB)
const INK = [35, 32, 29];
const MUTED = [107, 100, 89];
const ACCENT = [89, 81, 224];
const TERRACOTTA = [192, 103, 63];
const GREEN = [63, 138, 92];
const AMBER = [168, 121, 31];
const RULE = [235, 230, 221];

const MARGIN = 56;
const PAGE_W = 595.28; // A4 pt
const PAGE_H = 841.89;
const CONTENT_W = PAGE_W - MARGIN * 2;

function sanitizeFilename(s) {
  return (
    (s || "")
      .trim()
      .replace(/[\\/:*?"<>|]/g, "") // strip filesystem-illegal chars
      .replace(/\s+/g, " ")
      .trim() || "download"
  );
}

// Small layout engine over jsPDF: a vertical cursor with auto page-breaks.
function makeDoc() {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;

  function ensure(space) {
    if (y + space > PAGE_H - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  }

  function line(str, opts = {}) {
    const {
      size = 11,
      style = "normal",
      color = INK,
      gapAfter = 5,
      indent = 0,
    } = opts;
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const wrapped = doc.splitTextToSize(String(str ?? ""), CONTENT_W - indent);
    const lh = size * 1.4;
    for (const w of wrapped) {
      ensure(lh);
      doc.text(w, MARGIN + indent, y);
      y += lh;
    }
    y += gapAfter;
  }

  function gap(h) {
    y += h;
  }

  function rule() {
    ensure(14);
    doc.setDrawColor(RULE[0], RULE[1], RULE[2]);
    doc.setLineWidth(1);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 14;
  }

  function footer() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
    doc.text(
      "Generated by Hazel — AI Hiring Copilot",
      MARGIN,
      PAGE_H - MARGIN / 2
    );
  }

  return { doc, line, gap, rule, ensure, footer };
}

function heading(d, title, color) {
  d.line(title, { size: 13, style: "bold", color, gapAfter: 8 });
}

function numberedList(d, items, textOf, metaOf, metaLabel) {
  items.forEach((item, i) => {
    d.line(`${i + 1}.  ${textOf(item)}`, { size: 11, gapAfter: metaOf(item) ? 1 : 8 });
    const meta = metaOf(item);
    if (meta) {
      d.line(`${metaLabel}: ${meta}`, {
        size: 9.5,
        style: "italic",
        color: MUTED,
        indent: 16,
        gapAfter: 8,
      });
    }
  });
}

function bulletList(d, items, color) {
  if (!items || items.length === 0) {
    d.line("None identified.", { size: 11, color: MUTED, gapAfter: 6 });
    return;
  }
  items.forEach((item) => {
    d.line(`•  ${item}`, { size: 11, gapAfter: 6, indent: 2 });
  });
}

// ---- Public: Interview prep PDF ----
export function downloadInterviewPrepPdf({
  candidateName,
  roleTitle,
  technical = [],
  behavioral = [],
}) {
  const d = makeDoc();

  d.line("Interview Prep", { size: 22, style: "bold", color: INK, gapAfter: 4 });
  d.line(
    [candidateName, roleTitle].filter(Boolean).join("  ·  "),
    { size: 12, color: MUTED, gapAfter: 6 }
  );
  d.rule();

  heading(d, `Technical questions (${technical.length})`, ACCENT);
  numberedList(d, technical, (q) => q.question, (q) => q.targets_skill, "Targets");
  d.gap(6);

  heading(d, `Behavioral questions (${behavioral.length})`, TERRACOTTA);
  numberedList(d, behavioral, (q) => q.question, (q) => q.focus_area, "Focus");

  d.footer();
  d.doc.save(`${sanitizeFilename(`${candidateName}_${roleTitle}`)}.pdf`);
}

// ---- Public: Interview summary PDF ----
export function downloadInterviewSummaryPdf({ candidateName, summary }) {
  const d = makeDoc();

  d.line("Interview Summary", { size: 22, style: "bold", color: INK, gapAfter: 4 });
  if (candidateName) {
    d.line(candidateName, { size: 12, color: MUTED, gapAfter: 6 });
  }
  if (summary.recommended_verdict) {
    d.line(`Recommended verdict:  ${summary.recommended_verdict}`, {
      size: 12,
      style: "bold",
      color: ACCENT,
      gapAfter: 6,
    });
  }
  d.rule();

  heading(d, "Strengths", GREEN);
  bulletList(d, summary.strengths, GREEN);
  d.gap(6);

  heading(d, "Watch-outs", AMBER);
  bulletList(d, summary.weaknesses, AMBER);
  d.gap(6);

  if (summary.summary) {
    heading(d, "Overall", ACCENT);
    d.line(summary.summary, { size: 11, gapAfter: 6 });
  }

  d.footer();
  const base = candidateName
    ? `${candidateName}_InterviewSummary`
    : "Interview_Summary";
  d.doc.save(`${sanitizeFilename(base)}.pdf`);
}
